### ISSUE TITLE
Split acceptance tests from unit tests

### ISSUE THREAD

**Issue by eshamow** [slalompdx/control_spec_helper#31]

**Comment by dhgwilliam** [comment]
think this is done.

**Comment by eshamow** [comment]
I was wrong - not done - this is for the CSH tests, not the tests executed by the CSH :D

**Comment by dhgwilliam** [comment]
wait wait. this code is in the `Rakefile` in CSH's root:

```ruby
task unit: ['fixtures:shared_prep'] do
  exec 'bundle exec rspec -P spec/unit/*_spec.rb'
end

task acceptance: ['fixtures:prep'] do
  exec 'bundle exec rspec -P spec/tasks/*_spec.rb'
end
```

**Comment by eshamow** [comment]
Oh wow! They're undocumented so I assumed they weren't present when I did be rake -T. You are right! Thanks @dhgwilliam
